Fail if certificate missing
Fixes:

```
» curl localhost:3000/health
Cannot read property 'authorized' of undefined% 
```

On the server
```
 TypeError: Cannot read property 'authorized' of undefined
    at ClientCertStrategy.authenticate (/Projects/node_modules/passport-client-cert/src/index.js:27:17)
    at attempt (/Projects/node_modules/passport/lib/middleware/authenticate.js:348:16)
```